### ISSUE TITLE
[bug] - Failed to start the api server

### ISSUE THREAD

**Issue by littlenas** [littlenas/lavinda#3]
## Expected Behavior
When I cloned the repo and install dependencies,I start the server but didnt receive the endpoint with "Hello World"
```
npm start
```
## Current Behavior
server is listening but when I go to http://localhost:3000 , it doesn't work

## Possible Solution
update the express version and change the port number

## Steps to Reproduce
1. git clone the repo
2. npm install
3. go to http://localhost:3000
4. you will see blank screem

**Comment by nasxmo** [comment]
I already checked the issue. There is nothing wrong with the code. Try to upgrade your node js version to the latest and try to running the code again. I'll close the issue for now
